Lab3, Tabs, Kiseleva
reznikovkg/just-copy pull request #36
Opened 2023-04-02 17:50 UTC by evkiseleva

2023-04-02 18:43 UTC, reznikovkg commented
@oleyon @oleyon-labs провести проверку

2023-04-02 19:24 UTC, reznikovkg commented
@aver77 провести проверку

2023-04-02 20:27 UTC, oleyon-labs requested changes
Внести корректировки

2023-04-02 20:27 UTC, oleyon-labs commented on vue2/components/tab/Tab.vue
> +          <button class="tab__button" :class="{'tab__button__active':tab[0]==activeTab}" @click="()=>setDescription(tab)">{{ tab[0] }}</button>
Слишком длинная строка
Разбить по атрибутам на несколько строк

2023-04-02 20:27 UTC, oleyon-labs commented on vue2/components/tab/Tab.vue
> +        <div v-for="tab in content" v-bind:key="tab.id">
У tab, передаваемого из TabsKiseleva.vue нет поля id

2023-04-02 20:36 UTC, reznikovkg reviewed
Еще замечания

2023-04-02 20:36 UTC, reznikovkg commented on vue2/components/tab/Tab.vue
> +        <div v-for="tab in content" v-bind:key="tab.id">
`v-bind` не использовать. `v-bind:` и  `:` одно и то же. Использовать сокращенную форму `:`

2023-04-02 20:36 UTC, reznikovkg commented on vue2/components/tab/style/style.less
> +.container{
Отступ перед `{`

2023-04-02 20:36 UTC, reznikovkg commented on vue2/app/src/views/TabsKiseleva.vue
> +            'getTabs',
Можно использовать `getTabs` и не делать `tabs`

2023-04-02 20:36 UTC, reznikovkg commented on vue2/app/src/views/TabsKiseleva.vue
> +        <div v-for="(content, index) in tabs" :key="index">
Использовать `getTabs`

2023-04-02 20:36 UTC, reznikovkg commented on vue2/components/tab/README.md
> +  .myText{
Для документации это не нужно

2023-04-03 15:15 UTC, reznikovkg reviewed
Исправить

2023-04-03 15:15 UTC, reznikovkg commented on vue2/components/tab/Tab.vue
> +    <div class="tab">
Съехал отступ всего файла

2023-04-03 15:15 UTC, reznikovkg commented on vue2/components/tab/Tab.vue
> +        this.activeTab = this.content[0][0];
Что если передан пустой массив для `content`? Тут будет ошибка. Старайтесь избегать обращений к элементам по индексам

2023-04-03 16:19 UTC, evkiseleva commented
@reznikovkg  добавила проверку на пустоту, понимаю, что обращаться к элементу по индексу плохо, но не придумала другую реализацию

2023-04-03 16:21 UTC, merged